# Generated by Django 3.2.4 on 2021-12-18 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0002_auto_20211209_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_public', models.BooleanField(default=False)),
                ('operation_count', models.IntegerField(default=0)),
                ('proxy_url', models.CharField(max_length=200)),
                ('last_checked_at', models.DateTimeField(default=datetime.datetime(2021, 12, 18, 12, 28, 41, 459068, tzinfo=utc))),
                ('does_work', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_username', models.CharField(max_length=128)),
                ('account_id', models.CharField(max_length=32)),
                ('has_nitro', models.BooleanField()),
                ('has_gifts', models.BooleanField()),
                ('has_payments', models.BooleanField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tgbot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
