# Generated by Django 3.2.4 on 2021-12-19 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_manager', '0002_auto_20211218_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='request_count_from_last_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_checked_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 22, 27, 58, 943928, tzinfo=utc)),
        ),
    ]
